import Head from 'next/head'
import Nav from 'Components/Nav'
import Carousel from 'Components/Carousel'
import styles from '@/styles/main.module.css';
import ComponentContext, { DataContext } from 'Components/Context';
import { useContext, useEffect } from 'react';

export default function Home({dataProducts}) {
  return (
    <>
      <Head>
        <title>Fast buy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav/>
        <Carousel dataProducts={dataProducts} />
      </main>
    </>
  )
}


export const getServerSideProps = async () => {
  const data = await fetch('http://localhost:3000/api/products');
  const dataJson = await data.json();
  return {
    props: {
      dataProducts: dataJson
    }
  }
}
